version: '3'
services:
  web:
   image: tmiklu/php:fargate
   ports:
    - "80:80"
   logging:
     driver: awslogs
     options:
       awslogs-group: tutorial
       awslogs-region: us-east-1
       awslogs-stream-prefix: web
